# Generated by Django 6.0 on 2026-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('breakfast', models.BooleanField(default=False, verbose_name='صبحانه')),
                ('lunch', models.BooleanField(default=False, verbose_name='ناهار')),
                ('dinner', models.BooleanField(default=False, verbose_name='شام')),
            ],
        ),
    ]
