# Generated by Django 6.0 on 2026-01-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self', '0002_dailyfood'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationfood',
            name='fullname',
        ),
        migrations.AddField(
            model_name='reservationfood',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Self.student'),
            preserve_default=False,
        ),
    ]
