# Generated by Django 6.0 on 2026-01-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self', '0002_dailyfood'),
        ('user', '0002_remove_reservationfood_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Self.dailyfood')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Self.student')),
            ],
            options={
                'unique_together': {('student', 'daily_food')},
            },
        ),
        migrations.DeleteModel(
            name='ReservationFood',
        ),
    ]
