# Generated by Django 6.0 on 2026-01-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self', '0002_dailyfood'),
        ('user', '0003_reservation_delete_reservationfood'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.CharField(default='sun', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Self.student'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='lunch',
        ),
    ]
