# Generated by Django 6.0 on 2025-12-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_alter_friend_age_alter_friend_city_alter_friend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
