# Generated by Django 6.0 on 2026-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('national_code', models.IntegerField(blank=True, null=True)),
                ('ID_number', models.IntegerField(blank=True, null=True)),
                ('Inventory', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
