# Generated by Django 6.0 on 2026-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3, unique=True)),
                ('breakfast', models.CharField(blank=True, max_length=200, null=True, verbose_name='صبحانه')),
                ('lunch', models.CharField(blank=True, max_length=200, null=True, verbose_name='ناهار')),
                ('dinner', models.CharField(blank=True, max_length=200, null=True, verbose_name='شام')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت کل روز')),
            ],
        ),
    ]
